### ISSUE TITLE
Type error: 'oldDevice' is possibly 'undefined'.

### ISSUE THREAD

**Issue by EliasOlie** [PsychoLlama/media-devices#418]
## Problem Description

While using the `media-devices@0.4.0` package along with the `MediaDevices.enumerateDevices` method, I encountered a compilation error when attempting to build the project. Everything worked as expected during development, but upon trying to build the project, the following error was encountered:

./node_modules/.pnpm/media-devices@0.4.0/node_modules/media-devices/src/device-manager.ts:149:33
Type error: 'oldDevice' is possibly 'undefined'.

## Steps to Reproduce

1. Installed the `media-devices@0.4.0` package using pnpm.
2. Used the `MediaDevices.enumerateDevices` method in my code.
3. Upon attempting the build process, the aforementioned error was encountered.

## Temporary Solution

To work around the error, I needed to adjust the TypeScript configuration in the `tsconfig.json`, by removing the `strict` option and setting `noEmitOnError` to `false`.

## Additional Information

- React Version: 18.2.0
- media-devices Library Version: 0.4.0
- Node.js Version: 20.10.0

**Comment by PsychoLlama** [comment]
Thanks for the bug report. I wasn't able to repro, but I have a pretty good idea of what happened. I've published a release candidate as `media-devices@0.4.1-rc.1` (https://github.com/PsychoLlama/media-devices/pull/423). Would you give it a shot and see if it fixes the error?

If it works I'll push a stable version.

**Comment by PsychoLlama** [comment]
I ended up including this fix with `v0.5.0` as part of [another issue](https://github.com/PsychoLlama/media-devices/issues/436). This should be resolved. I'm going to close the ticket but let me know if it gives you any more trouble :+1:
